### ISSUE TITLE
inline: fit to container

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/pickr#17]
the inline version should fit to its container width.  If this is going to be a huge pain, let me know before you get started

**Comment by Antonio-Laguna** [comment]
It's not a huge pain but style gets funky on certain widths:

http://cl.ly/image/16363G1Q3V2a
http://cl.ly/image/323426300S3n

IMHO this is something you should handle per-case since things can go awry easily. Container will have a new class when the PRs are merged. 

If there is something I didn't understand let me know!

**Comment by jgallen23** [comment]
Can you expose a variable that I can use in the less mixin to set the size?  Other option is to switch everything to percentages
